/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Session */
        post: operations["new_session_session_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_session__session_id__get"];
        put?: never;
        post?: never;
        /** End Session */
        delete: operations["end_session_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Turn */
        post: operations["submit_turn_session__session_id__turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}/turn/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Turn Stream */
        post: operations["submit_turn_stream_session__session_id__turn_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}/cast/{npc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cast */
        get: operations["get_cast_session__session_id__cast__npc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}/couples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Couples */
        get: operations["get_couples_session__session_id__couples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/{session_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_session__session_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiExchange */
        ApiExchange: {
            /** Speaker Id */
            speaker_id: string;
            /** Speaker Name */
            speaker_name: string;
            /** Player Dialogue */
            player_dialogue: string;
            /** Npc Dialogue */
            npc_dialogue: string;
            /** Npc Tone */
            npc_tone: string;
            /** Npc Mood After */
            npc_mood_after: string;
        };
        /** ApiKnownFact */
        ApiKnownFact: {
            /** Fact Key */
            fact_key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Source */
            source: string;
            /** Source Npc Id */
            source_npc_id: string | null;
            /** Confidence */
            confidence: number;
            /** Citation */
            citation: string;
            /**
             * Group
             * @enum {string}
             */
            group: "confirmed" | "heard" | "trivia";
        };
        /** ApiMemory */
        ApiMemory: {
            /** Holder Id */
            holder_id: string;
            /** Subject Id */
            subject_id: string;
            /** Content */
            content: string;
            /** Emotional Weight */
            emotional_weight: number;
            /** Source */
            source: string;
            /** Tags */
            tags: string[];
            /** Formed On Turn */
            formed_on_turn: number;
        };
        /** ApiRelationship */
        ApiRelationship: {
            /** Affection */
            affection: number;
            /** Chemistry */
            chemistry: number;
            /** Trust */
            trust: number;
            /** Friendship */
            friendship: number;
            /**
             * Connection
             * @default 0
             */
            connection: number;
            /**
             * Connection Label
             * @default Just met
             */
            connection_label: string;
            /**
             * Connection Tier
             * @default 0
             */
            connection_tier: number;
        };
        /** AudienceState */
        AudienceState: {
            /** Public Perception */
            public_perception: number;
            /** Recent Delta */
            recent_delta: number | null;
            /**
             * Trend
             * @enum {string}
             */
            trend: "rising" | "falling" | "steady";
        };
        /** AvailableAction */
        AvailableAction: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Target Id */
            target_id: string | null;
            /** Intent Id */
            intent_id: string | null;
            /** Option Index */
            option_index: number | null;
            /**
             * Audience Hint
             * @enum {string}
             */
            audience_hint: "+" | "-" | "";
            /** Risk */
            risk: string | null;
            /** Stat Used */
            stat_used: string | null;
            /** Description */
            description?: string | null;
        };
        /** CastDetail */
        CastDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Gender */
            gender: string;
            /** Archetype */
            archetype: string;
            /** Mood */
            mood: string;
            /** Location */
            location: string;
            /** Backstory */
            backstory: string;
            /** Familiarity */
            familiarity: number;
            relationship: components["schemas"]["ApiRelationship"];
            /** Type On Paper */
            ideal_match: {
                [key: string]: unknown | null;
            };
            /** Known Facts */
            known_facts: components["schemas"]["ApiKnownFact"][];
            /** Memories */
            memories: components["schemas"]["ApiMemory"][];
            /** Coupled With */
            coupled_with: string | null;
            /** Eliminated */
            eliminated: boolean;
        };
        /** CoupleSummary */
        CoupleSummary: {
            /** Partner A Id */
            partner_a_id: string;
            /** Partner B Id */
            partner_b_id: string;
            /** Partner A Name */
            partner_a_name: string;
            /** Partner B Name */
            partner_b_name: string;
            /** Strength */
            strength: number;
            /** Formed On Day */
            formed_on_day: number;
            /** Formed Via */
            formed_via: string;
            /** Formed Via Label */
            formed_via_label: string;
            /** Rebound */
            rebound: boolean;
            /** Is Player Couple */
            is_player_couple: boolean;
        };
        /** CouplesResponse */
        CouplesResponse: {
            /** Couples */
            couples: components["schemas"]["CoupleSummary"][];
            /** Singles */
            singles: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbreakerSummary */
        HeartbreakerSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Gender */
            gender: string;
            /** Archetype */
            archetype: string;
            /** Mood */
            mood: string;
            /** Location Id */
            location_id: string;
            /** Location Label */
            location_label: string;
            /** Eliminated */
            eliminated: boolean;
            /** Coupled */
            coupled: boolean;
            /** Familiarity With Player */
            familiarity_with_player: number;
        };
        /** NewSessionRequest */
        NewSessionRequest: {
            /**
             * Archetype
             * @enum {string}
             */
            archetype: "heartthrob" | "class_clown" | "loyal_friend";
            /**
             * Player Name
             * @default You
             */
            player_name: string;
            /**
             * Player Gender
             * @default man
             * @enum {string}
             */
            player_gender: "man" | "woman";
            /** Seed */
            seed?: number | null;
            /** Mock Llm */
            mock_llm?: boolean | null;
        };
        /** PlayerState */
        PlayerState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Gender */
            gender: string;
            /** Archetype Id */
            archetype_id: string;
            /** Public Perception */
            public_perception: number;
            /** Stats */
            stats: {
                [key: string]: number;
            };
            /** Memories */
            memories: components["schemas"]["ApiMemory"][];
        };
        /** SessionResponse */
        SessionResponse: {
            /** Session Id */
            session_id: string;
            state: components["schemas"]["SessionState"];
            /** Available Actions */
            available_actions: components["schemas"]["AvailableAction"][];
        };
        /** SessionState */
        SessionState: {
            /** Session Id */
            session_id: string;
            /** Schema Version */
            schema_version: number;
            /** Seed */
            seed: number;
            /** Day */
            day: number;
            /** Phase */
            phase: string;
            /** Phase Label */
            phase_label: string;
            /** Turn Index */
            turn_index: number;
            /** Location Id */
            location_id: string;
            /** Location Label */
            location_label: string;
            /** Resort */
            resort: string;
            /** Resort Label */
            resort_label: string;
            /** Phase Clock */
            phase_clock: {
                [key: string]: unknown;
            };
            player: components["schemas"]["PlayerState"];
            /** Heartbreakers */
            heartbreakers: components["schemas"]["HeartbreakerSummary"][];
            /** Couples */
            couples: components["schemas"]["CoupleSummary"][];
            audience: components["schemas"]["AudienceState"];
            /** Pending Pair Proposal */
            pending_pair_proposal: {
                [key: string]: unknown;
            } | null;
            /** Outcome */
            outcome: string | null;
            /** Active Conversation Target Id */
            active_conversation_target_id: string | null;
            /** Resort Snapshot */
            resort_snapshot: {
                [key: string]: string[];
            };
            /** Daily Recaps */
            daily_recaps: {
                [key: string]: unknown;
            }[];
        };
        /** TurnRequest */
        TurnRequest: {
            /** Kind */
            kind: string;
            /** Target Id */
            target_id?: string | null;
            /** Intent Id */
            intent_id?: string | null;
            /** Option Index */
            option_index?: number | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** TurnResponse */
        TurnResponse: {
            state: components["schemas"]["SessionState"];
            exchange: components["schemas"]["ApiExchange"] | null;
            /** Available Actions */
            available_actions: components["schemas"]["AvailableAction"][];
            /** Ceremony Events */
            ceremony_events: {
                [key: string]: unknown;
            }[];
            /** Event Narration */
            event_narration: {
                [key: string]: unknown;
            } | null;
            /** Audience Delta */
            audience_delta: number | null;
            /** Audience Delta Reason */
            audience_delta_reason: string | null;
            /** Memories Formed */
            memories_formed: {
                [key: string]: unknown;
            }[];
            /** Background Activity */
            background_activity: {
                [key: string]: unknown;
            }[];
            /** Connection Shift */
            connection_shift?: string | null;
            /** State Hash */
            state_hash: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Schema Version */
            schema_version: number;
            /** Api Version */
            api_version: string;
            /** Build */
            build: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    new_session_session_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_turn_session__session_id__turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_turn_stream_session__session_id__turn_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cast_session__session_id__cast__npc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                npc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CastDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_couples_session__session_id__couples_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouplesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_session__session_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
