/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Session */
        post: operations["new_session_session_new_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Checkpoints
         * @description Return loadable saved-state options for the main-menu picker.
         */
        get: operations["checkpoints_checkpoints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/from-checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Session From Checkpoint
         * @description Open a new session preloaded from a saved checkpoint.
         *
         *     The on-the-wire shape matches `POST /session/new` so the client can route
         *     to the same `/play/[sessionId]` page after either path. The new
         *     ``session_id`` is freshly minted (the checkpoint's own session_id is
         *     intentionally not reused — multiple branches can spring off one save).
         */
        post: operations["session_from_checkpoint_session_from_checkpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** View Session */
        post: operations["view_session_session_view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Turn */
        post: operations["submit_turn_session_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/turn/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Turn Stream */
        post: operations["submit_turn_stream_session_turn_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session/cast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Cast */
        post: operations["get_cast_session_cast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllocationView */
        AllocationView: {
            /**
             * Role
             * @enum {string}
             */
            role: "kiss" | "wed" | "pass";
            /** Subject Id */
            subject_id: string;
        };
        /**
         * AnsweredMinigameRoundView
         * @description Display-safe outcome of one completed minigame round.
         */
        AnsweredMinigameRoundView: {
            /** Round Index */
            round_index: number;
            /** Chosen Label */
            chosen_label: string | null;
            /** Correct Label */
            correct_label: string | null;
            /** Is Correct */
            is_correct: boolean;
            /** Points */
            points: number;
            /** Reaction Line */
            reaction_line: string | null;
        };
        /** ApiExchange */
        ApiExchange: {
            /** Speaker Id */
            speaker_id: string;
            /** Speaker Name */
            speaker_name: string;
            /** Player Dialogue */
            player_dialogue: string;
            /** Npc Dialogue */
            npc_dialogue: string;
            /** Npc Tone */
            npc_tone: string;
            /** Npc Mood After */
            npc_mood_after: string;
        };
        /** ApiKnownFact */
        ApiKnownFact: {
            /** Fact Key */
            fact_key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Source */
            source: string;
            /** Source Npc Id */
            source_npc_id: string | null;
            /** Confidence */
            confidence: number;
            /** Citation */
            citation: string;
            /**
             * Group
             * @enum {string}
             */
            group: "confirmed" | "heard" | "trivia";
        };
        /** ApiMemory */
        ApiMemory: {
            /** Id */
            id: string;
            /** Holder Id */
            holder_id: string;
            /** Subject Id */
            subject_id: string;
            /** Content */
            content: string;
            /** Emotional Weight */
            emotional_weight: number;
            /** Source */
            source: string;
            /** Tags */
            tags: string[];
            /** Formed On Turn */
            formed_on_turn: number;
        };
        /** ApiRelationship */
        ApiRelationship: {
            /** Affection */
            affection: number;
            /** Chemistry */
            chemistry: number;
            /** Trust */
            trust: number;
            /** Friendship */
            friendship: number;
            /**
             * Connection
             * @default 0
             */
            connection: number;
            /**
             * Connection Label
             * @default Just met
             */
            connection_label: string;
            /**
             * Connection Tier
             * @default 0
             */
            connection_tier: number;
        };
        /** AudienceState */
        AudienceState: {
            /** Public Perception */
            public_perception: number;
            /** Recent Delta */
            recent_delta: number | null;
            /**
             * Trend
             * @enum {string}
             */
            trend: "rising" | "falling" | "steady";
        };
        /** AvailableAction */
        AvailableAction: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Target Id */
            target_id: string | null;
            /** Intent Id */
            intent_id: string | null;
            /** Option Index */
            option_index: number | null;
            /**
             * Audience Hint
             * @enum {string}
             */
            audience_hint: "+" | "-" | "";
            /** Risk */
            risk: string | null;
            /** Stat Used */
            stat_used: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Description */
            description?: string | null;
        };
        /** CastDetail */
        CastDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Gender */
            gender: string;
            /** Archetype */
            archetype: string;
            /** Mood */
            mood: string;
            /** Location */
            location: string;
            /** Backstory */
            backstory: string;
            /** Familiarity */
            familiarity: number;
            relationship: components["schemas"]["ApiRelationship"];
            /** Ideal Match */
            ideal_match: {
                [key: string]: unknown | null;
            };
            /** Known Facts */
            known_facts: components["schemas"]["ApiKnownFact"][];
            /** Memories */
            memories: components["schemas"]["ApiMemory"][];
            /** Coupled With */
            coupled_with: string | null;
            /** Eliminated */
            eliminated: boolean;
        };
        /**
         * CastRequest
         * @description Stateless cast detail request.
         */
        CastRequest: {
            persisted: components["schemas"]["PersistedSession"];
            /** Npc Id */
            npc_id: string;
        };
        /** CheckpointListResponse */
        CheckpointListResponse: {
            /** Checkpoints */
            checkpoints: components["schemas"]["CheckpointSummaryResponse"][];
        };
        /** CheckpointStartRequest */
        CheckpointStartRequest: {
            /** Name */
            name: string;
            /** Mock Llm */
            mock_llm?: boolean | null;
        };
        /**
         * CheckpointSummaryResponse
         * @description One main-menu entry for a loadable saved state.
         */
        CheckpointSummaryResponse: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Day */
            day: number;
            /** Phase */
            phase: string;
            /**
             * Source
             * @enum {string}
             */
            source: "bundled" | "local";
        };
        /** CompatibilityQuizBoardView */
        CompatibilityQuizBoardView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "compatibility_quiz";
            latest_answer?: components["schemas"]["AnsweredMinigameRoundView"] | null;
        };
        /** CoupleSummary */
        CoupleSummary: {
            /** Partner A Id */
            partner_a_id: string;
            /** Partner B Id */
            partner_b_id: string;
            /** Partner A Name */
            partner_a_name: string;
            /** Partner B Name */
            partner_b_name: string;
            /** Strength */
            strength: number;
            /** Formed On Day */
            formed_on_day: number;
            /** Formed Via */
            formed_via: string;
            /** Formed Via Label */
            formed_via_label: string;
            /** Rebound */
            rebound: boolean;
            /** Is Player Couple */
            is_player_couple: boolean;
        };
        /** CouplesQuizBoardView */
        CouplesQuizBoardView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "couples_quiz";
            /** Player Answer */
            player_answer?: string | null;
            /** Partner Answer */
            partner_answer?: string | null;
            /** Aligned */
            aligned?: boolean | null;
        };
        /**
         * DailyRecapItemView
         * @description One display-safe recap item.
         */
        DailyRecapItemView: {
            /**
             * Section
             * @enum {string}
             */
            section: "your_day" | "while_busy";
            /** Speaker Label */
            speaker_label: string;
            /** Content */
            content: string;
            /**
             * Emphasis
             * @enum {string}
             */
            emphasis: "standard" | "strong";
        };
        /**
         * DailyRecapView
         * @description One complete player-facing recap.
         */
        DailyRecapView: {
            /** Day */
            day: number;
            /** Resort Id */
            resort_id: string;
            /** Resort Label */
            resort_label: string;
            /** Items */
            items?: components["schemas"]["DailyRecapItemView"][];
        };
        /** FacetScoreView */
        FacetScoreView: {
            /** Facet */
            facet: string;
            /** Score */
            score: number;
        };
        /** FinalCouplesBoardView */
        FinalCouplesBoardView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "final_couples";
            /** Facets */
            facets?: components["schemas"]["FacetScoreView"][];
            /** Final Tally */
            final_tally?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbreakerSummary */
        HeartbreakerSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Gender */
            gender: string;
            /** Archetype */
            archetype: string;
            /** Mood */
            mood: string;
            /** Location Id */
            location_id: string;
            /** Location Label */
            location_label: string;
            /** Eliminated */
            eliminated: boolean;
            /** Coupled */
            coupled: boolean;
            /** Familiarity With Player */
            familiarity_with_player: number;
        };
        /** KissWedPassBoardView */
        KissWedPassBoardView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "kiss_wed_pass";
            /** Allocations */
            allocations?: components["schemas"]["AllocationView"][];
        };
        /** LieDetectorBoardView */
        LieDetectorBoardView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "lie_detector";
            /** Subject Id */
            subject_id?: string | null;
            /** Verdict */
            verdict?: ("truth_told" | "truth_suspected" | "lie_caught" | "lie_believed") | null;
            /** Needle Percent */
            needle_percent?: number | null;
        };
        /**
         * MinigameKind
         * @description Canonical minigame discriminator.
         * @enum {string}
         */
        MinigameKind: "compatibility_quiz" | "heart_rate" | "couples_quiz" | "lie_detector" | "kiss_wed_pass" | "final_couples";
        /** MinigameRoundView */
        MinigameRoundView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "round";
            kind: components["schemas"]["MinigameKind"];
            /** Round Index */
            round_index: number;
            /** Round Count */
            round_count: number;
            /** Narration */
            narration: string;
            /** Question */
            question: string;
            /** Target Id */
            target_id: string | null;
            /** Answered Rounds */
            answered_rounds?: components["schemas"]["AnsweredMinigameRoundView"][];
            /** Board */
            board: components["schemas"]["CompatibilityQuizBoardView"] | components["schemas"]["CouplesQuizBoardView"] | components["schemas"]["PulseRaceBoardView"] | components["schemas"]["LieDetectorBoardView"] | components["schemas"]["KissWedPassBoardView"] | components["schemas"]["FinalCouplesBoardView"];
        };
        /** MinigameWrapView */
        MinigameWrapView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "wrap";
            kind: components["schemas"]["MinigameKind"];
            /** Round Count */
            round_count: number;
            /** Narration */
            narration: string;
            /**
             * Classification
             * @enum {string}
             */
            classification: "success" | "partial" | "failure";
            /** Total Points */
            total_points: number;
            /** Audience Delta */
            audience_delta: number;
            /** Answered Rounds */
            answered_rounds?: components["schemas"]["AnsweredMinigameRoundView"][];
            /** Board */
            board: components["schemas"]["CompatibilityQuizBoardView"] | components["schemas"]["CouplesQuizBoardView"] | components["schemas"]["PulseRaceBoardView"] | components["schemas"]["LieDetectorBoardView"] | components["schemas"]["KissWedPassBoardView"] | components["schemas"]["FinalCouplesBoardView"];
        };
        /**
         * NewSessionEnvelope
         * @description Initial session payload: a renderable view plus the blob the client persists.
         */
        NewSessionEnvelope: {
            view: components["schemas"]["SessionResponse"];
            persisted: components["schemas"]["PersistedSession"];
        };
        /** NewSessionRequest */
        NewSessionRequest: {
            /**
             * Archetype
             * @enum {string}
             */
            archetype: "heartthrob" | "class_clown" | "loyal_friend";
            /**
             * Player Name
             * @default You
             */
            player_name: string;
            /**
             * Player Gender
             * @default man
             * @enum {string}
             */
            player_gender: "man" | "woman";
            /** Seed */
            seed?: number | null;
            /** Mock Llm */
            mock_llm?: boolean | null;
        };
        /**
         * PersistedSession
         * @description Self-contained session payload exchanged with the client.
         *
         *     Versioned so future shape changes don't strand in-flight games. ``user_id`` is
         *     reserved for when accounts land — always ``None`` for anonymous play.
         */
        PersistedSession: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Session Id */
            session_id?: string;
            /** User Id */
            user_id?: string | null;
            /** Rng State */
            rng_state: unknown[];
            /** Game State */
            game_state: {
                [key: string]: unknown;
            };
            /**
             * Mock Llm
             * @default true
             */
            mock_llm: boolean;
        };
        /** PlayerState */
        PlayerState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Gender */
            gender: string;
            /** Archetype Id */
            archetype_id: string;
            /** Public Perception */
            public_perception: number;
            /** Stats */
            stats: {
                [key: string]: number;
            };
            /** Memories */
            memories: components["schemas"]["ApiMemory"][];
        };
        /** PulseRaceBoardView */
        PulseRaceBoardView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "heart_rate";
            /** Readings */
            readings?: components["schemas"]["PulseReadingView"][];
        };
        /** PulseReadingView */
        PulseReadingView: {
            /** Performer Id */
            performer_id: string;
            /** Observer Id */
            observer_id: string;
            /** Bpm */
            bpm: number;
            /** Chemistry */
            chemistry: number;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Session Id */
            session_id: string;
            state: components["schemas"]["SessionState"];
            /** Available Actions */
            available_actions: components["schemas"]["AvailableAction"][];
        };
        /** SessionState */
        SessionState: {
            /** Session Id */
            session_id: string;
            /** Schema Version */
            schema_version: number;
            /** Seed */
            seed: number;
            /** Day */
            day: number;
            /** Phase */
            phase: string;
            /** Phase Label */
            phase_label: string;
            /** Turn Index */
            turn_index: number;
            /** Location Id */
            location_id: string;
            /** Location Label */
            location_label: string;
            /** Resort */
            resort: string;
            /** Resort Label */
            resort_label: string;
            /** Phase Clock */
            phase_clock: {
                [key: string]: unknown;
            };
            player: components["schemas"]["PlayerState"];
            /** Heartbreakers */
            heartbreakers: components["schemas"]["HeartbreakerSummary"][];
            /** Couples */
            couples: components["schemas"]["CoupleSummary"][];
            audience: components["schemas"]["AudienceState"];
            /** Pending Pair Proposal */
            pending_pair_proposal: {
                [key: string]: unknown;
            } | null;
            /** Pending Challenge */
            pending_challenge?: (components["schemas"]["MinigameRoundView"] | components["schemas"]["MinigameWrapView"]) | null;
            /** Outcome */
            outcome: string | null;
            /** Active Conversation Target Id */
            active_conversation_target_id: string | null;
            /** Resort Snapshot */
            resort_snapshot: {
                [key: string]: string[];
            };
            /** Daily Recaps */
            daily_recaps: components["schemas"]["DailyRecapView"][];
            /**
             * Intros Greetings
             * @default {}
             */
            intros_greetings: {
                [key: string]: string;
            };
        };
        /**
         * TurnEnvelope
         * @description Stateless turn request: client sends the full persisted blob plus the action.
         */
        TurnEnvelope: {
            persisted: components["schemas"]["PersistedSession"];
            action: components["schemas"]["TurnRequest"];
        };
        /** TurnRequest */
        TurnRequest: {
            /** Kind */
            kind: string;
            /** Target Id */
            target_id?: string | null;
            /** Intent Id */
            intent_id?: string | null;
            /** Option Index */
            option_index?: number | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** TurnResponse */
        TurnResponse: {
            state: components["schemas"]["SessionState"];
            exchange: components["schemas"]["ApiExchange"] | null;
            /** Available Actions */
            available_actions: components["schemas"]["AvailableAction"][];
            /** Ceremony Events */
            ceremony_events: {
                [key: string]: unknown;
            }[];
            /** Event Narration */
            event_narration: {
                [key: string]: unknown;
            } | null;
            /** Audience Delta */
            audience_delta: number | null;
            /** Audience Delta Reason */
            audience_delta_reason: string | null;
            /** Memories Formed */
            memories_formed: {
                [key: string]: unknown;
            }[];
            /** Background Activity */
            background_activity: {
                [key: string]: unknown;
            }[];
            /** Connection Shift */
            connection_shift?: string | null;
            /** State Hash */
            state_hash: string;
        };
        /**
         * TurnResponseEnvelope
         * @description Stateless turn response: the updated view plus the new persisted blob.
         */
        TurnResponseEnvelope: {
            view: components["schemas"]["TurnResponse"];
            persisted: components["schemas"]["PersistedSession"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Schema Version */
            schema_version: number;
            /** Api Version */
            api_version: string;
            /** Build */
            build: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    new_session_session_new_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewSessionEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkpoints_checkpoints_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointListResponse"];
                };
            };
        };
    };
    session_from_checkpoint_session_from_checkpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckpointStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewSessionEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    view_session_session_view_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersistedSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_turn_session_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnEnvelope"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponseEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_turn_stream_session_turn_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnEnvelope"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cast_session_cast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CastRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CastDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
