"""Context and message-chain helpers for Heartbreaker Voice."""

from __future__ import annotations

from typing import Literal, cast

from pydantic import BaseModel, ConfigDict, Field

from src.game.content.loader import load_content
from src.game.content.models import ContentIndex
from src.game.engine.actions import ActionKind
from src.game.engine.compatibility import revealed_preferences
from src.game.engine.intents import get_intent
from src.game.engine.rules import MechanicalResult
from src.game.state.models import (
    Conversation,
    ExchangeRecord,
    FollowUpOption,
    GameState,
    Gender,
    HeartbreakerState,
    Memory,
    Mood,
)


class Exchange(BaseModel):
    """Dialogue exchange generated by the Heartbreaker Voice agent."""

    model_config = ConfigDict(extra="forbid")

    player_dialogue: str
    npc_dialogue: str
    npc_tone: Literal[
        "warm",
        "flirty",
        "suspicious",
        "amused",
        "cold",
        "vulnerable",
        "playful",
        "defensive",
    ]
    npc_mood_after: Mood


class HeartbreakerVoiceContext(BaseModel):
    """Visible, non-mechanical context given to the Heartbreaker Voice agent."""

    model_config = ConfigDict(extra="forbid")

    day: int
    phase: str
    location: str
    location_flavor: str
    player_gender: str
    npc_gender: str
    npc_name: str
    npc_archetype: str
    npc_backstory: str
    npc_persona_summary: str
    archetype_prose: str
    big5_summary: str
    attachment_style: str
    revealed_preferences: dict[str, object]
    npc_mood: Mood
    relationship_summary: str
    intent_category: str
    intent_label: str
    is_intro: bool = False
    stat_used: str
    tags: list[str]
    outcome: str
    private_chat_context: str | None = None
    private_chat_departure_names: list[str] = Field(default_factory=list)
    interrupted_conversation_names: list[str] = Field(default_factory=list)
    mechanical_change_summary: str
    others_present: list[str]
    cast_names: list[str]
    cast_pronouns: list[str]
    gossip_subject_names: list[str]
    recent_exchange_topics: list[str]
    gossip_eligible_memories: list[str]


class NewTurnContext(BaseModel):
    """Concise current-turn context used in the conversation message chain."""

    model_config = ConfigDict(extra="forbid")

    scene: str
    turn: str


def heartbreaker_voice_context(
    state: GameState,
    result: MechanicalResult,
    content: ContentIndex | None = None,
) -> HeartbreakerVoiceContext:
    """Build the visible context for one Heartbreaker Voice call."""
    target = target_for_result(state, result)
    intent_id = result.action.intent_id
    if intent_id is None:
        raise ValueError("conversation result is missing intent_id")
    gossip: Memory | None = None
    try:
        intent = get_intent(intent_id)
        intent_category = intent.category.value
        intent_label = intent.label
        stat_used = intent.stat_used
        tags = intent.tags
    except ValueError:
        gossip = _gossip_memory_for_intent(state, intent_id)
        if result.private_chat_attempt is not None and intent_id == "private_chat_rejected":
            intent_category = "private_chat"
            intent_label = (
                "The player asked this Heartbreaker for a private chat during another conversation. "
                "The invitation failed: the Heartbreaker should deflect, stay busy, and not warmly accept."
            )
            stat_used = "spark"
        else:
            intent_category = "gossip" if gossip is not None else "contextual"
            if gossip is None:
                selected_option = _selected_follow_up_option(state, intent_id)
                intent_label = (
                    _contextual_intent_label(intent_id)
                    if selected_option is None
                    else (
                        f"The player selected this exact menu action: {selected_option.label}. "
                        "Continue the concrete subject in the most recent NPC line; do not replace it "
                        "with a related topic or broader subject."
                    )
                )
                if selected_option is not None and intent_id == "honest_vulnerable":
                    intent_label += (
                        " The player's reciprocal disclosure must first answer or connect to that "
                        "concrete subject. It cannot switch to a generic statement about home, life, "
                        "or feeling complicated."
                    )
            elif intent_id.startswith("share_gossip:"):
                subject_is_heartbreaker = any(
                    heartbreaker.id == gossip.subject_id for heartbreaker in state.heartbreakers
                )
                if subject_is_heartbreaker:
                    intent_label = (
                        f"Share with {target.name} the gossip you heard about "
                        f"{_subject_name(state, gossip.subject_id)}: {gossip.content}"
                    )
                else:
                    intent_label = (
                        f"Tell {target.name} about something you witnessed in the "
                        f"resort: {gossip.content}"
                    )
            else:
                intent_label = (
                    f"Ask about {_subject_name(state, gossip.subject_id)}: {gossip.content}"
                )
            stat_used = "contextual"
        tags = result.tags
    index = content if content is not None else load_content()
    location_content = index.locations.get(state.location_id.value)
    archetype = index.archetypes.get(target.archetype)
    others = [
        heartbreaker.name
        for heartbreaker in state.heartbreakers
        if heartbreaker.id != target.id
        and heartbreaker.location_id == state.location_id
        and not heartbreaker.eliminated
    ]
    return HeartbreakerVoiceContext(
        day=state.day,
        phase=state.phase.value,
        location=state.location_id.value,
        location_flavor="" if location_content is None else location_content.body,
        player_gender=state.player.gender.value,
        npc_gender=target.gender.value,
        npc_name=target.name,
        npc_archetype=target.archetype,
        npc_backstory=_backstory_context(
            target,
            force_public=result.action.kind == ActionKind.INTRODUCE_TO,
        ),
        npc_persona_summary=_persona_summary(
            target,
            force_public=result.action.kind == ActionKind.INTRODUCE_TO,
        ),
        archetype_prose="" if archetype is None else archetype.body,
        big5_summary=_big5_summary(target),
        attachment_style=target.attachment.value,
        revealed_preferences=revealed_preferences(target),
        npc_mood=target.mood,
        relationship_summary=_relationship_summary(
            target,
            force_first_meeting=result.action.kind == ActionKind.INTRODUCE_TO,
        ),
        intent_category=intent_category,
        intent_label=intent_label,
        is_intro=result.action.kind == ActionKind.INTRODUCE_TO,
        stat_used=stat_used,
        tags=tags,
        outcome="success" if result.success else "miss",
        private_chat_context=_private_chat_context(state, result),
        private_chat_departure_names=_private_chat_departure_names(state, result),
        interrupted_conversation_names=_interrupted_conversation_names(state, result),
        mechanical_change_summary=_mechanical_change_summary(result, target.id),
        others_present=[] if result.action.kind == ActionKind.INTRODUCE_TO else others,
        cast_names=sorted({heartbreaker.name for heartbreaker in state.heartbreakers}),
        cast_pronouns=_cast_pronouns(state),
        gossip_subject_names=_gossip_subject_names_for_intent(state, intent_id, gossip),
        recent_exchange_topics=_recent_exchange_topics(state),
        gossip_eligible_memories=_gossip_eligible_memories(state, target.id),
    )


def new_turn_context(context: HeartbreakerVoiceContext) -> NewTurnContext:
    """Convert full validation context into concise message-chain context."""
    scene = "\n".join(
        [
            f"Day: {context.day}",
            f"Phase: {context.phase}",
            f"Location: {context.location}",
            f"Location flavor: {context.location_flavor}",
            f"Player gender: {context.player_gender}",
            f"Heartbreaker gender: {context.npc_gender}",
            f"Name: {context.npc_name}",
            "Conversation partner: the player. The Heartbreaker is replying to the player, not to themselves.",
            f"Backstory: {context.npc_backstory}",
            f"Internal persona summary: {context.npc_persona_summary}",
            f"Archetype voice: {context.archetype_prose}",
            f"Big Five: {context.big5_summary}",
            f"Attachment style: {context.attachment_style}",
            f"Known preferences: {context.revealed_preferences}",
            f"Current mood before this exchange: {context.npc_mood.value}",
            f"How they feel about the player right now: {context.relationship_summary}",
        ]
    )
    turn = "\n".join(
        [
            f"Category: {context.intent_category}",
            f"Specific intent: {context.intent_label}",
            f"Player stat used: {context.stat_used}",
            f"Tags: {', '.join(context.tags)}",
            f"Mechanical outcome: {context.outcome}",
            f"Private chat context: {context.private_chat_context or 'none'}",
            "Closed conversation after accepted interruption: "
            f"{_closed_interruption_context(context.interrupted_conversation_names)}",
            f"Mechanical changes: {context.mechanical_change_summary}",
            f"Others present: {_list_or_none(context.others_present)}",
            f"Allowed gossip subjects this turn: {_list_or_none(context.gossip_subject_names)}",
            "Cast pronouns (use exactly these for anyone you mention — never guess from a name): "
            f"{_list_or_none(context.cast_pronouns)}",
            f"Recent exchange topics: {_list_or_none(context.recent_exchange_topics)}",
            f"Gossip eligible memories: {_list_or_none(context.gossip_eligible_memories)}",
            "Write the exchange now.",
        ]
    )
    return NewTurnContext(scene=scene, turn=turn)


def build_voice_messages(
    state: GameState,
    conversation: Conversation | None,
    current: NewTurnContext,
) -> list[dict[str, str]]:
    """Build OpenAI message input with prior exchanges as native turns."""
    messages = [{"role": "user", "content": current.scene}]
    if conversation is not None:
        for record in conversation.exchanges:
            messages.append({"role": "user", "content": _prior_turn_user_message(record)})
            messages.append({"role": "assistant", "content": _prior_exchange_json(record)})
    guard = _avoid_repetition_directive(conversation, state.recent_player_lines)
    messages.append({"role": "user", "content": _turn_with_guard(current.turn, guard)})
    return messages


def _turn_with_guard(turn: str, guard: str | None) -> str:
    """Splice an anti-repetition guard in just before the final write cue.

    The nano model does not reliably self-regulate against re-running the same
    sentence opening turn after turn even though the prior exchanges are right
    there in the thread, so we name the already-used openings explicitly. Keep
    the message count and roles unchanged so the chain contract holds.
    """
    if not guard:
        return turn
    marker = "Write the exchange now."
    if turn.endswith(marker):
        return f"{turn[: -len(marker)]}{guard}\n{marker}"
    return f"{turn}\n{guard}"


def _avoid_repetition_directive(
    conversation: Conversation | None,
    recent_player_lines: list[str] | None = None,
    *,
    max_items: int = 8,
) -> str | None:
    """List opening phrases already used so the model varies its next opener.

    Draws from two sources: the active conversation's own exchanges (so a long
    chat does not re-run the same sentence shape) and ``recent_player_lines`` —
    a resort-wide rolling buffer of the player's recent spoken lines. The second
    source is what de-duplicates openers *across* separate conversations, most
    visibly the one-at-a-time intro round where each heartbreaker is a fresh thread
    that otherwise can't see the line the player just used on the last heartbreaker.

    Only the player's lines carry across conversations: NPC voices differ by
    character, so cross-character NPC overlap is not a repetition problem.

    Returns ``None`` when there is nothing to avoid yet (fresh conversation and
    empty resort-wide buffer)."""
    openings: list[str] = []
    if conversation is not None:
        for record in conversation.exchanges:
            for line in (record.player_dialogue, record.npc_dialogue):
                opening = _line_opening(line)
                if opening:
                    openings.append(opening)
    for line in recent_player_lines or []:
        opening = _line_opening(line)
        if opening:
            openings.append(opening)
    distinct = list(dict.fromkeys(openings))
    if not distinct:
        return None
    if len(distinct) > max_items:
        distinct = distinct[-max_items:]
    quoted = "; ".join(f'"{opening}"' for opening in distinct)
    history_note = (
        " Do not repeat a fact or anecdote already established in this conversation."
        if conversation is not None and conversation.exchanges
        else ""
    )
    return (
        f"Anti-repetition guard. Do not copy these recent openings: {quoted}. "
        "Vary the wording, not the facts. An ordinary direct line is better than an "
        "invented observation, event, prop, callback, or character detail."
        f"{history_note}"
    )


def _line_opening(line: str, *, words: int = 6) -> str:
    """First few words of a line, ignoring a leading italic stage direction.

    Six words (not the first three or four) so near-identical greeting frames —
    "I thought I'd come say hi" vs "I figured I'd come over and say hi" — surface
    their shared move in the avoid-list, not just their literal first token.
    """
    text = line.strip()
    if text.startswith("*"):
        close = text.find("*", 1)
        if close != -1:
            text = text[close + 1 :].strip()
    tokens = text.split()
    if not tokens:
        return ""
    return " ".join(tokens[:words])


def recent_player_openings(
    conversation: Conversation | None,
    recent_player_lines: list[str] | None = None,
) -> list[str]:
    """Openings of the player's own recent spoken lines.

    Used by the deterministic opener-freshness backstop in the agent: the
    advisory guard *asks* the model not to repeat, but a small model will still
    reopen with the same reassurance/greeting frame, so the agent needs a hard,
    case-folded set of the player's prior openings to detect and re-prompt a
    near-verbatim repeat. Player lines only — NPC voices differ by character, so
    a coincidental NPC overlap should not force the player's line to be redrawn.
    """
    openings: list[str] = []
    if conversation is not None:
        for record in conversation.exchanges:
            opening = _line_opening(record.player_dialogue)
            if opening:
                openings.append(opening)
    for line in recent_player_lines or []:
        opening = _line_opening(line)
        if opening:
            openings.append(opening)
    return list(dict.fromkeys(openings))


def reused_player_opening(player_line: str, used_openings: list[str]) -> str | None:
    """Return the colliding opening if ``player_line`` reopens with a used one.

    Comparison is case-folded so "You don't need to have it" and "you don't need
    to have it" count as the same opener.
    """
    opening = _line_opening(player_line)
    if not opening:
        return None
    folded = {used.casefold() for used in used_openings}
    return opening if opening.casefold() in folded else None


def target_for_result(state: GameState, result: MechanicalResult) -> HeartbreakerState:
    target_id = result.action.target_id
    for heartbreaker in state.heartbreakers:
        if heartbreaker.id == target_id:
            return heartbreaker
    raise ValueError(f"conversation target not found: {target_id}")


def _prior_turn_user_message(record: ExchangeRecord) -> str:
    outcome = "success" if record.success else "miss"
    return "\n".join(
        [
            f"Prior intent: {record.intent_id}",
            f"Prior outcome: {outcome}",
            f"Prior tags: {', '.join(record.tags)}",
        ]
    )


def _prior_exchange_json(record: ExchangeRecord) -> str:
    return Exchange(
        player_dialogue=record.player_dialogue,
        npc_dialogue=record.npc_dialogue,
        npc_tone=cast(
            Literal[
                "warm",
                "flirty",
                "suspicious",
                "amused",
                "cold",
                "vulnerable",
                "playful",
                "defensive",
            ],
            record.npc_tone,
        ),
        npc_mood_after=record.npc_mood_after,
    ).model_dump_json()


def _relationship_summary(
    target: HeartbreakerState,
    *,
    force_first_meeting: bool = False,
) -> str:
    relationship = target.relationship
    familiarity = target.familiarity_with_player
    rapport = (
        "This is the first one-on-one greeting with the player. No prior private exchange exists."
        if force_first_meeting
        else _rapport_phrase(familiarity)
    )
    return (
        f"affection {relationship.affection}, chemistry {relationship.chemistry}, "
        f"trust {relationship.trust}, friendship {relationship.friendship}, "
        f"familiarity {familiarity}/100. {rapport}"
    )


def _rapport_phrase(familiarity: int) -> str:
    """Tell the voice whether this is a stranger or someone already known.

    Without this the opener of a *re-started* conversation (the player walking
    back up after an earlier chat closed) only sees raw relationship numbers and
    tends to cold-open like a first meeting. Familiarity is the same 0-100 signal
    every other system uses, so a high value should warm the re-greeting."""
    if familiarity >= 60:
        return (
            "You already know the player well from earlier conversations — if you are "
            "opening a new chat, greet them like someone you have real history with, "
            "not a stranger you just met."
        )
    if familiarity >= 25:
        return (
            "You have already met the player and talked before — you are past first "
            "introductions. If you are opening a new chat, pick up like people who "
            "already know each other; do not re-introduce yourself or greet them like a "
            "stranger."
        )
    return "You barely know the player yet — you are still in the early, getting-to-know-you stage."


def _big5_summary(target: HeartbreakerState) -> str:
    big5 = target.big5
    return (
        f"openness {big5.openness}, conscientiousness {big5.conscientiousness}, "
        f"extraversion {big5.extraversion}, agreeableness {big5.agreeableness}, "
        f"neuroticism {big5.neuroticism}"
    )


def _persona_summary(target: HeartbreakerState, *, force_public: bool = False) -> str:
    persona = target.trait_card.persona
    familiarity = target.familiarity_with_player
    if force_public or familiarity < 25:
        return (
            f"Voice notes: {persona.voice_notes}\n"
            "This is an early conversation. Keep the character's deeper motives private; "
            "do not explain or confess them."
        )
    if familiarity < 60:
        return (
            f"{persona.one_line}\n"
            f"Voice notes: {persona.voice_notes}\n"
            f"Contradictions: {', '.join(persona.contradictions)}\n"
            "Let contradictions appear as subtext rather than self-analysis."
        )
    return (
        f"{persona.one_line}\n"
        f"Voice notes: {persona.voice_notes}\n"
        f"Contradictions: {', '.join(persona.contradictions)}\n"
        f"Secret engine: {persona.secret_engine}"
    )


def _backstory_context(target: HeartbreakerState, *, force_public: bool = False) -> str:
    """Expose public facts early and reserve authored history for earned chats."""
    if not force_public and target.familiarity_with_player >= 25:
        return target.backstory
    facts = target.trait_card.core_traits
    values = [
        str(fact.value)
        for fact in (facts.get("age"), facts.get("occupation"), facts.get("hometown"))
        if fact is not None
    ]
    return "Public profile: " + ", ".join(values) + "."


def _mechanical_change_summary(result: MechanicalResult, target_id: str) -> str:
    delta = result.relationship_deltas.get(target_id)
    if delta is None:
        return "No relationship change."
    parts = [f"{name} {value:+d}" for name, value in delta.model_dump().items() if value != 0]
    return ", ".join(parts) if parts else "No relationship change."


def _private_chat_context(state: GameState, result: MechanicalResult) -> str | None:
    attempt = result.private_chat_attempt
    if attempt is None:
        return None
    target_name = _subject_name(state, attempt.target_id)
    other_names = [
        _subject_name(state, participant_id)
        for participant_id in attempt.blocked_participants
        if participant_id != attempt.target_id
    ]
    source = (
        f"{target_name} away from {', '.join(other_names)}"
        if other_names
        else f"{target_name} away from another conversation"
    )
    topic = f" about {attempt.blocked_topic}" if attempt.blocked_topic else ""
    outcome = (
        "opened a private chat with" if attempt.success else "failed to open a private chat with"
    )
    return (
        f"The player just {outcome} {source}{topic}. Acknowledge that social "
        "interruption before moving into the selected intent."
    )


def _private_chat_departure_names(state: GameState, result: MechanicalResult) -> list[str]:
    attempt = result.private_chat_attempt
    if attempt is None or not attempt.success:
        return []
    return [
        _subject_name(state, participant_id)
        for participant_id in attempt.blocked_participants
        if participant_id != attempt.target_id
    ]


def _interrupted_conversation_names(
    state: GameState,
    result: MechanicalResult,
) -> list[str]:
    if result.action.intent_id != "accept_interruption" or result.action.target_id is None:
        return []
    return [
        _subject_name(state, actor_id)
        for actor_id in result.relationship_deltas
        if actor_id != result.action.target_id
    ]


def _list_or_none(values: list[str]) -> str:
    return ", ".join(values) if values else "none"


def _closed_interruption_context(values: list[str]) -> str:
    if not values:
        return "none"
    return (
        f"{', '.join(values)}. The player ended that chat by accepting this interruption. "
        "The new speaker should acknowledge cutting in once. Do not promise to resume the old "
        "chat or return to its topic."
    )


def _recent_exchange_topics(state: GameState) -> list[str]:
    conversation = state.active_conversation
    if conversation is None:
        return []
    return list(conversation.accumulated_tags)


def _gossip_eligible_memories(state: GameState, target_id: str) -> list[str]:
    for heartbreaker in state.heartbreakers:
        if heartbreaker.id == target_id:
            return [
                f"{memory.subject_id}: {memory.content}"
                for memory in heartbreaker.memories
                if memory.subject_id != "player" and memory.emotional_weight >= 4
            ]
    return []


def _intent_label(intent_id: str | None) -> str:
    if intent_id is None:
        return "chat"
    try:
        return get_intent(intent_id).label
    except ValueError:
        return intent_id.replace("_", " ")


def _contextual_intent_label(intent_id: str) -> str:
    labels = {
        "accept_interruption": (
            "The player gives this Heartbreaker the floor after they interrupted another "
            "conversation. The Heartbreaker says they wanted to speak with the player. No more "
            "specific reason was recorded: do not invent what another contestant said, did, or wanted."
        ),
        "engage_approach": (
            "The player welcomes this Heartbreaker after they approached. The Heartbreaker opens "
            "with the reason they came over."
        ),
    }
    return labels.get(intent_id, intent_id.replace("_", " "))


def _selected_follow_up_option(state: GameState, intent_id: str) -> FollowUpOption | None:
    conversation = state.active_conversation
    if conversation is None or conversation.pending_options is None:
        return None
    return next(
        (
            option
            for option in conversation.pending_options.options
            if option.intent_kind == intent_id
        ),
        None,
    )


def _gossip_memory_for_intent(state: GameState, intent_id: str) -> Memory | None:
    if intent_id.startswith("share_gossip:"):
        # Player-shared gossip: the source memory lives in the player's own
        # memory list. Resolving it lets the voice prompt name the subject and
        # whitelists that subject so validate_exchange never treats the natural
        # subject mention as a leaked hidden Heartbreaker.
        memory_id = intent_id.removeprefix("share_gossip:")
        for memory in state.player.memories:
            if memory.id == memory_id:
                return memory
        return None
    if not intent_id.startswith("ask_gossip:") or state.active_conversation is None:
        return None
    memory_id = intent_id.removeprefix("ask_gossip:")
    for memory in state.active_conversation.gossip_offers:
        if memory.id == memory_id:
            return memory
    return None


def _cast_pronouns(state: GameState) -> list[str]:
    """`Name: pronouns` for every living heartbreaker so the voice never guesses.

    Many heartbreaker names are unisex (Jules, Sam, Riley, Noor, Jordan, Blake), so a
    speaker referring to a *third party* by name — most often when sharing or
    answering gossip, or reacting to someone else in the room — can pick the wrong
    pronoun off the name alone. This roster is supplied separately from
    ``cast_names``/``others_present`` (which the leak validator matches verbatim),
    so it carries the gender signal without disturbing leak detection.
    """
    return [
        f"{heartbreaker.name}: {'she/her' if heartbreaker.gender == Gender.WOMAN else 'he/him'}"
        for heartbreaker in state.heartbreakers
        if not heartbreaker.eliminated
    ]


def _subject_name(state: GameState, subject_id: str) -> str:
    for heartbreaker in state.heartbreakers:
        if heartbreaker.id == subject_id:
            return heartbreaker.name
    return subject_id


def _gossip_subject_names_for_intent(
    state: GameState,
    intent_id: str,
    gossip: Memory | None,
) -> list[str]:
    subject_ids: list[str] = []
    if gossip is not None:
        subject_ids.append(gossip.subject_id)
        # Any cast member named in the gossip's own content is fair game for the
        # NPC to mention back — the player is the one bringing them up. Whitelist
        # them so validate_exchange never treats a natural echo as a leaked hidden
        # Heartbreaker (which would otherwise burn every retry and dead-screen the
        # turn). These ids are derived once at the memory-creation boundary
        # (memory._mentioned_subject_ids) and read structurally here — no regex
        # scan of prose at exchange time.
        subject_ids.extend(gossip.mentioned_subject_ids)
    if intent_id.startswith("ask_gossip:about_"):
        subject_ids.append(intent_id.removeprefix("ask_gossip:about_"))
    names = [_subject_name(state, subject_id) for subject_id in subject_ids]
    return list(dict.fromkeys(names))


__all__ = [
    "Exchange",
    "HeartbreakerVoiceContext",
    "NewTurnContext",
    "_intent_label",
    "build_voice_messages",
    "heartbreaker_voice_context",
    "new_turn_context",
    "target_for_result",
]
