"""Islander Voice agent for single-exchange conversations.

Design sources:
- 03-LLM-Architecture.md: Dialogue AI
- 11-Conversation-Flow.md: Single Exchange Generation

Implementation rule:
The agent receives resolved mechanics and writes dialogue only. It never
mutates GameState, decides success, or changes relationship math.
"""

from __future__ import annotations

import os
import re
from collections.abc import Callable
from pathlib import Path
from typing import Literal

from openai import OpenAI
from pydantic import BaseModel, ConfigDict

from src.game.content.loader import load_content
from src.game.content.models import ContentIndex
from src.game.engine.compatibility import revealed_preferences
from src.game.engine.intents import get_intent
from src.game.engine.rules import MechanicalResult
from src.game.state.models import GameState, IslanderState, Memory, Mood

ISLANDER_VOICE_MODEL = "gpt-4.1-mini"
VALID_TONES = {
    "warm",
    "flirty",
    "suspicious",
    "amused",
    "cold",
    "vulnerable",
    "playful",
    "defensive",
}
KNOWN_NAMES = {"Chloe", "Maya", "Liam", "Aisha"}


class Exchange(BaseModel):
    """Dialogue exchange generated by the Islander Voice agent."""

    model_config = ConfigDict(extra="forbid")

    player_dialogue: str
    npc_dialogue: str
    npc_tone: Literal[
        "warm",
        "flirty",
        "suspicious",
        "amused",
        "cold",
        "vulnerable",
        "playful",
        "defensive",
    ]
    npc_mood_after: Mood


class IslanderVoiceContext(BaseModel):
    """Visible, non-mechanical context given to the Islander Voice agent."""

    model_config = ConfigDict(extra="forbid")

    day: int
    phase: str
    location: str
    location_flavor: str
    npc_name: str
    npc_archetype: str
    archetype_prose: str
    big5_summary: str
    attachment_style: str
    revealed_preferences: dict[str, object]
    npc_mood: Mood
    relationship_summary: str
    intent_category: str
    intent_label: str
    stat_used: str
    tags: list[str]
    outcome: str
    mechanical_change_summary: str
    others_present: list[str]
    recent_history: str


IslanderVoiceFn = Callable[[GameState, MechanicalResult], Exchange]


class OpenAIIslanderVoice:
    """Single Islander Voice agent backed by the OpenAI Responses API."""

    def __init__(
        self,
        *,
        model: str = ISLANDER_VOICE_MODEL,
        content: ContentIndex | None = None,
    ) -> None:
        load_dotenv_local()
        self._client = OpenAI()
        self._model = model
        self._content = content if content is not None else load_content()

    def generate(self, state: GameState, result: MechanicalResult) -> Exchange:
        """Generate one structured exchange for a resolved mechanical result."""
        context = islander_voice_context(state, result, self._content)
        response = self._client.responses.parse(
            model=self._model,
            instructions=Path("src/game/agents/prompts/islander_voice.md").read_text(
                encoding="utf-8"
            ),
            input=_render_context(context),
            text_format=Exchange,
            max_output_tokens=320,
        )
        exchange = response.output_parsed
        if exchange is None:
            raise ValueError("Islander Voice returned no parsed Exchange")
        validate_exchange(exchange, context)
        return exchange


def islander_voice_context(
    state: GameState,
    result: MechanicalResult,
    content: ContentIndex | None = None,
) -> IslanderVoiceContext:
    """Build the visible context for one Islander Voice call."""
    target = _target_for_result(state, result)
    intent_id = result.action.intent_id
    if intent_id is None:
        raise ValueError("conversation result is missing intent_id")
    try:
        intent = get_intent(intent_id)
        intent_category = intent.category.value
        intent_label = intent.label
        stat_used = intent.stat_used
        tags = intent.tags
    except ValueError:
        gossip = _gossip_memory_for_intent(state, intent_id)
        if result.pull_attempt is not None and intent_id == "pull_rejected":
            intent_category = "pull"
            intent_label = (
                "The player tried to pull this Islander away from another conversation. "
                "The pull failed: the Islander should deflect, stay busy, and not warmly accept."
            )
            stat_used = "graft"
        else:
            intent_category = "gossip" if gossip is not None else "contextual"
            intent_label = (
                f"Ask about {_subject_name(state, gossip.subject_id)}: {gossip.content}"
                if gossip is not None
                else intent_id.replace("_", " ")
            )
            stat_used = "contextual"
        tags = result.tags
    index = content if content is not None else load_content()
    location_content = index.locations.get(state.location_id.value)
    archetype = index.archetypes.get(target.archetype)
    others = [
        islander.name
        for islander in state.islanders
        if islander.id != target.id
        and islander.location_id == state.location_id
        and not islander.eliminated
    ]
    return IslanderVoiceContext(
        day=state.day,
        phase=state.phase.value,
        location=state.location_id.value,
        location_flavor="" if location_content is None else location_content.body,
        npc_name=target.name,
        npc_archetype=target.archetype,
        archetype_prose="" if archetype is None else archetype.body,
        big5_summary=_big5_summary(target),
        attachment_style=target.attachment.value,
        revealed_preferences=revealed_preferences(target),
        npc_mood=target.mood,
        relationship_summary=_relationship_summary(target),
        intent_category=intent_category,
        intent_label=intent_label,
        stat_used=stat_used,
        tags=tags,
        outcome="success" if result.success else "miss",
        mechanical_change_summary=_mechanical_change_summary(result, target.id),
        others_present=others,
        recent_history=_recent_history(state),
    )


def mock_islander_voice(state: GameState, result: MechanicalResult) -> Exchange:
    """Return deterministic mock dialogue for non-LLM tests and replays."""
    target = _target_for_result(state, result)
    intent_label = _intent_label(result.action.intent_id)
    if result.success:
        return Exchange(
            player_dialogue=f"I wanted to say this properly, {target.name}: {intent_label}.",
            npc_dialogue="*smiles* I hear you. That actually feels good coming from you.",
            npc_tone="warm",
            npc_mood_after=Mood.HAPPY,
        )
    return Exchange(
        player_dialogue=f"I am trying to say this right, {target.name}: {intent_label}.",
        npc_dialogue="*pauses* I get what you mean, but that did not fully land for me.",
        npc_tone="defensive",
        npc_mood_after=Mood.CONTENT,
    )


def validate_exchange(exchange: Exchange, context: IslanderVoiceContext) -> None:
    """Fail loud if generated dialogue violates the exchange contract."""
    joined = f"{exchange.player_dialogue} {exchange.npc_dialogue}"
    word_count = len(joined.split())
    if not 20 <= word_count <= 150:
        raise ValueError(
            f"exchange word count out of bounds: {word_count}; exchange={exchange!r}"
        )
    if re.search(r"\d", joined):
        raise ValueError(f"exchange contains digits; exchange={exchange!r}")
    allowed = {context.npc_name, *context.others_present}
    hidden_mentions = sorted(name for name in KNOWN_NAMES - allowed if name in joined)
    if hidden_mentions:
        raise ValueError(
            f"exchange mentions hidden islander(s) {hidden_mentions}; exchange={exchange!r}"
        )
    if exchange.npc_tone not in VALID_TONES:
        raise ValueError(f"invalid npc_tone: {exchange.npc_tone}")


def load_dotenv_local(path: Path = Path(".env.local")) -> None:
    """Load local environment variables without printing secrets."""
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())


def _render_context(context: IslanderVoiceContext) -> str:
    return "\n".join(
        [
            f"Day: {context.day}",
            f"Phase: {context.phase}",
            f"Location: {context.location}",
            f"Location flavor: {context.location_flavor}",
            f"Name: {context.npc_name}",
            f"Archetype voice: {context.archetype_prose}",
            f"Big Five: {context.big5_summary}",
            f"Attachment style: {context.attachment_style}",
            f"Known preferences: {context.revealed_preferences}",
            f"Current mood before this exchange: {context.npc_mood.value}",
            f"How they feel about the player right now: {context.relationship_summary}",
            f"Category: {context.intent_category}",
            f"Specific intent: {context.intent_label}",
            f"Player stat used: {context.stat_used}",
            f"Tags: {', '.join(context.tags)}",
            f"Mechanical outcome: {context.outcome}",
            f"Mechanical changes: {context.mechanical_change_summary}",
            f"Others present: {_list_or_none(context.others_present)}",
            f"Recent exchange history: {context.recent_history}",
            "Write the exchange now.",
        ]
    )


def _target_for_result(state: GameState, result: MechanicalResult) -> IslanderState:
    target_id = result.action.target_id
    for islander in state.islanders:
        if islander.id == target_id:
            return islander
    raise ValueError(f"conversation target not found: {target_id}")


def _relationship_summary(target: IslanderState) -> str:
    relationship = target.relationship
    return (
        f"affection {relationship.affection}, chemistry {relationship.chemistry}, "
        f"trust {relationship.trust}, friendship {relationship.friendship}"
    )


def _big5_summary(target: IslanderState) -> str:
    big5 = target.big5
    return (
        f"openness {big5.openness}, conscientiousness {big5.conscientiousness}, "
        f"extraversion {big5.extraversion}, agreeableness {big5.agreeableness}, "
        f"neuroticism {big5.neuroticism}"
    )


def _mechanical_change_summary(result: MechanicalResult, target_id: str) -> str:
    delta = result.relationship_deltas.get(target_id)
    if delta is None:
        return "No relationship change."
    parts = [
        f"{name} {value:+d}"
        for name, value in delta.model_dump().items()
        if value != 0
    ]
    return ", ".join(parts) if parts else "No relationship change."


def _list_or_none(values: list[str]) -> str:
    return ", ".join(values) if values else "none"


def _recent_history(state: GameState) -> str:
    conversation = state.active_conversation
    if conversation is None or not conversation.exchanges:
        return "No prior exchanges in this conversation."
    return "\n".join(
        f"- You: {record.player_dialogue}\n  {record.npc_tone}: {record.npc_dialogue}"
        for record in conversation.exchanges[-2:]
    )


def _intent_label(intent_id: str | None) -> str:
    if intent_id is None:
        return "chat"
    try:
        return get_intent(intent_id).label
    except ValueError:
        return intent_id.replace("_", " ")


def _gossip_memory_for_intent(state: GameState, intent_id: str) -> Memory | None:
    if not intent_id.startswith("ask_gossip:") or state.active_conversation is None:
        return None
    memory_id = intent_id.removeprefix("ask_gossip:")
    for memory in state.active_conversation.gossip_offers:
        if memory.id == memory_id:
            return memory
    return None


def _subject_name(state: GameState, subject_id: str) -> str:
    for islander in state.islanders:
        if islander.id == subject_id:
            return islander.name
    return subject_id
