"""Context and message-chain helpers for Islander Voice."""

from __future__ import annotations

from typing import Literal, cast

from pydantic import BaseModel, ConfigDict

from src.game.content.loader import load_content
from src.game.content.models import ContentIndex
from src.game.engine.compatibility import revealed_preferences
from src.game.engine.intents import get_intent
from src.game.engine.rules import MechanicalResult
from src.game.state.models import (
    Conversation,
    ExchangeRecord,
    GameState,
    IslanderState,
    Memory,
    Mood,
)


class Exchange(BaseModel):
    """Dialogue exchange generated by the Islander Voice agent."""

    model_config = ConfigDict(extra="forbid")

    player_dialogue: str
    npc_dialogue: str
    npc_tone: Literal[
        "warm",
        "flirty",
        "suspicious",
        "amused",
        "cold",
        "vulnerable",
        "playful",
        "defensive",
    ]
    npc_mood_after: Mood


class IslanderVoiceContext(BaseModel):
    """Visible, non-mechanical context given to the Islander Voice agent."""

    model_config = ConfigDict(extra="forbid")

    day: int
    phase: str
    location: str
    location_flavor: str
    player_gender: str
    npc_gender: str
    npc_name: str
    npc_archetype: str
    npc_backstory: str
    npc_persona_summary: str
    archetype_prose: str
    big5_summary: str
    attachment_style: str
    revealed_preferences: dict[str, object]
    npc_mood: Mood
    relationship_summary: str
    intent_category: str
    intent_label: str
    stat_used: str
    tags: list[str]
    outcome: str
    pull_context: str | None = None
    mechanical_change_summary: str
    others_present: list[str]
    cast_names: list[str]
    gossip_subject_names: list[str]
    recent_exchange_topics: list[str]
    gossip_eligible_memories: list[str]


class NewTurnContext(BaseModel):
    """Concise current-turn context used in the conversation message chain."""

    model_config = ConfigDict(extra="forbid")

    scene: str
    turn: str


def islander_voice_context(
    state: GameState,
    result: MechanicalResult,
    content: ContentIndex | None = None,
) -> IslanderVoiceContext:
    """Build the visible context for one Islander Voice call."""
    target = target_for_result(state, result)
    intent_id = result.action.intent_id
    if intent_id is None:
        raise ValueError("conversation result is missing intent_id")
    gossip: Memory | None = None
    try:
        intent = get_intent(intent_id)
        intent_category = intent.category.value
        intent_label = intent.label
        stat_used = intent.stat_used
        tags = intent.tags
    except ValueError:
        gossip = _gossip_memory_for_intent(state, intent_id)
        if result.pull_attempt is not None and intent_id == "pull_rejected":
            intent_category = "pull"
            intent_label = (
                "The player tried to pull this Islander away from another conversation. "
                "The pull failed: the Islander should deflect, stay busy, and not warmly accept."
            )
            stat_used = "graft"
        else:
            intent_category = "gossip" if gossip is not None else "contextual"
            intent_label = (
                f"Ask about {_subject_name(state, gossip.subject_id)}: {gossip.content}"
                if gossip is not None
                else intent_id.replace("_", " ")
            )
            stat_used = "contextual"
        tags = result.tags
    index = content if content is not None else load_content()
    location_content = index.locations.get(state.location_id.value)
    archetype = index.archetypes.get(target.archetype)
    others = [
        islander.name
        for islander in state.islanders
        if islander.id != target.id
        and islander.location_id == state.location_id
        and not islander.eliminated
    ]
    return IslanderVoiceContext(
        day=state.day,
        phase=state.phase.value,
        location=state.location_id.value,
        location_flavor="" if location_content is None else location_content.body,
        player_gender=state.player.gender.value,
        npc_gender=target.gender.value,
        npc_name=target.name,
        npc_archetype=target.archetype,
        npc_backstory=target.backstory,
        npc_persona_summary=_persona_summary(target),
        archetype_prose="" if archetype is None else archetype.body,
        big5_summary=_big5_summary(target),
        attachment_style=target.attachment.value,
        revealed_preferences=revealed_preferences(target),
        npc_mood=target.mood,
        relationship_summary=_relationship_summary(target),
        intent_category=intent_category,
        intent_label=intent_label,
        stat_used=stat_used,
        tags=tags,
        outcome="success" if result.success else "miss",
        pull_context=_pull_context(state, result),
        mechanical_change_summary=_mechanical_change_summary(result, target.id),
        others_present=others,
        cast_names=sorted({islander.name for islander in state.islanders}),
        gossip_subject_names=_gossip_subject_names_for_intent(state, intent_id, gossip),
        recent_exchange_topics=_recent_exchange_topics(state),
        gossip_eligible_memories=_gossip_eligible_memories(state, target.id),
    )


def new_turn_context(context: IslanderVoiceContext) -> NewTurnContext:
    """Convert full validation context into concise message-chain context."""
    scene = "\n".join(
        [
            f"Day: {context.day}",
            f"Phase: {context.phase}",
            f"Location: {context.location}",
            f"Location flavor: {context.location_flavor}",
            f"Player gender: {context.player_gender}",
            f"Islander gender: {context.npc_gender}",
            f"Name: {context.npc_name}",
            "Conversation partner: the player. The Islander is replying to the player, not to themselves.",
            f"Backstory: {context.npc_backstory}",
            f"Internal persona summary: {context.npc_persona_summary}",
            f"Archetype voice: {context.archetype_prose}",
            f"Big Five: {context.big5_summary}",
            f"Attachment style: {context.attachment_style}",
            f"Known preferences: {context.revealed_preferences}",
            f"Current mood before this exchange: {context.npc_mood.value}",
            f"How they feel about the player right now: {context.relationship_summary}",
        ]
    )
    turn = "\n".join(
        [
            f"Category: {context.intent_category}",
            f"Specific intent: {context.intent_label}",
            f"Player stat used: {context.stat_used}",
            f"Tags: {', '.join(context.tags)}",
            f"Mechanical outcome: {context.outcome}",
            f"Pull context: {context.pull_context or 'none'}",
            f"Mechanical changes: {context.mechanical_change_summary}",
            f"Others present: {_list_or_none(context.others_present)}",
            f"Allowed gossip subjects this turn: {_list_or_none(context.gossip_subject_names)}",
            f"Recent exchange topics: {_list_or_none(context.recent_exchange_topics)}",
            f"Gossip eligible memories: {_list_or_none(context.gossip_eligible_memories)}",
            "Write the exchange now.",
        ]
    )
    return NewTurnContext(scene=scene, turn=turn)


def build_voice_messages(
    state: GameState,
    conversation: Conversation | None,
    current: NewTurnContext,
) -> list[dict[str, str]]:
    """Build OpenAI message input with prior exchanges as native turns."""
    del state
    messages = [{"role": "user", "content": current.scene}]
    if conversation is not None:
        for record in conversation.exchanges:
            messages.append({"role": "user", "content": _prior_turn_user_message(record)})
            messages.append({"role": "assistant", "content": _prior_exchange_json(record)})
    messages.append({"role": "user", "content": current.turn})
    return messages


def target_for_result(state: GameState, result: MechanicalResult) -> IslanderState:
    target_id = result.action.target_id
    for islander in state.islanders:
        if islander.id == target_id:
            return islander
    raise ValueError(f"conversation target not found: {target_id}")


def _prior_turn_user_message(record: ExchangeRecord) -> str:
    outcome = "success" if record.success else "miss"
    return "\n".join(
        [
            f"Prior intent: {record.intent_id}",
            f"Prior outcome: {outcome}",
            f"Prior tags: {', '.join(record.tags)}",
        ]
    )


def _prior_exchange_json(record: ExchangeRecord) -> str:
    return Exchange(
        player_dialogue=record.player_dialogue,
        npc_dialogue=record.npc_dialogue,
        npc_tone=cast(
            Literal[
                "warm",
                "flirty",
                "suspicious",
                "amused",
                "cold",
                "vulnerable",
                "playful",
                "defensive",
            ],
            record.npc_tone,
        ),
        npc_mood_after=record.npc_mood_after,
    ).model_dump_json()


def _relationship_summary(target: IslanderState) -> str:
    relationship = target.relationship
    return (
        f"affection {relationship.affection}, chemistry {relationship.chemistry}, "
        f"trust {relationship.trust}, friendship {relationship.friendship}"
    )


def _big5_summary(target: IslanderState) -> str:
    big5 = target.big5
    return (
        f"openness {big5.openness}, conscientiousness {big5.conscientiousness}, "
        f"extraversion {big5.extraversion}, agreeableness {big5.agreeableness}, "
        f"neuroticism {big5.neuroticism}"
    )


def _persona_summary(target: IslanderState) -> str:
    persona = target.trait_card.persona
    return (
        f"{persona.one_line}\n"
        f"Voice notes: {persona.voice_notes}\n"
        f"Contradictions: {', '.join(persona.contradictions)}\n"
        f"Secret engine: {persona.secret_engine}"
    )


def _mechanical_change_summary(result: MechanicalResult, target_id: str) -> str:
    delta = result.relationship_deltas.get(target_id)
    if delta is None:
        return "No relationship change."
    parts = [
        f"{name} {value:+d}"
        for name, value in delta.model_dump().items()
        if value != 0
    ]
    return ", ".join(parts) if parts else "No relationship change."


def _pull_context(state: GameState, result: MechanicalResult) -> str | None:
    attempt = result.pull_attempt
    if attempt is None:
        return None
    target_name = _subject_name(state, attempt.target_id)
    other_names = [
        _subject_name(state, participant_id)
        for participant_id in attempt.blocked_participants
        if participant_id != attempt.target_id
    ]
    source = (
        f"{target_name} away from {', '.join(other_names)}"
        if other_names
        else f"{target_name} away from another conversation"
    )
    topic = f" about {attempt.blocked_topic}" if attempt.blocked_topic else ""
    outcome = "succeeded at pulling" if attempt.success else "failed to pull"
    return (
        f"The player just {outcome} {source}{topic}. Acknowledge that social "
        "interruption before moving into the selected intent."
    )


def _list_or_none(values: list[str]) -> str:
    return ", ".join(values) if values else "none"


def _recent_exchange_topics(state: GameState) -> list[str]:
    conversation = state.active_conversation
    if conversation is None:
        return []
    return list(conversation.accumulated_tags)


def _gossip_eligible_memories(state: GameState, target_id: str) -> list[str]:
    for islander in state.islanders:
        if islander.id == target_id:
            return [
                f"{memory.subject_id}: {memory.content}"
                for memory in islander.memories
                if memory.subject_id != "player" and memory.emotional_weight >= 4
            ]
    return []


def _intent_label(intent_id: str | None) -> str:
    if intent_id is None:
        return "chat"
    try:
        return get_intent(intent_id).label
    except ValueError:
        return intent_id.replace("_", " ")


def _gossip_memory_for_intent(state: GameState, intent_id: str) -> Memory | None:
    if not intent_id.startswith("ask_gossip:") or state.active_conversation is None:
        return None
    memory_id = intent_id.removeprefix("ask_gossip:")
    for memory in state.active_conversation.gossip_offers:
        if memory.id == memory_id:
            return memory
    return None


def _subject_name(state: GameState, subject_id: str) -> str:
    for islander in state.islanders:
        if islander.id == subject_id:
            return islander.name
    return subject_id


def _gossip_subject_names_for_intent(
    state: GameState,
    intent_id: str,
    gossip: Memory | None,
) -> list[str]:
    subject_ids: list[str] = []
    if gossip is not None:
        subject_ids.append(gossip.subject_id)
    if intent_id.startswith("ask_gossip:about_"):
        subject_ids.append(intent_id.removeprefix("ask_gossip:about_"))
    names = [_subject_name(state, subject_id) for subject_id in subject_ids]
    return list(dict.fromkeys(names))


__all__ = [
    "Exchange",
    "IslanderVoiceContext",
    "NewTurnContext",
    "_intent_label",
    "build_voice_messages",
    "islander_voice_context",
    "new_turn_context",
    "target_for_result",
]
