"""Markdown and small text helpers for review packets."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def notes(records: list[dict[str, Any]], final_hash: str | None, llm_mode: str) -> str:
    """Render packet notes markdown."""
    conversation_turns = sum(1 for record in records if record.get("exchange") is not None)
    villa_turns = sum(
        1
        for record in records
        if isinstance(record.get("agent_commits"), dict)
        and record["agent_commits"].get("villa_update") is not None
    )
    return f"""# Notes

## What I noticed

This packet renders one recorded playthrough from trace data. It contains
{len(records)} turn(s), {conversation_turns} player conversation turn(s), and
{villa_turns} turn(s) with recorded villa agent commits.

LLM mode: `{llm_mode}`. {plain_llm_mode_note(llm_mode)}

## What felt good

The report keeps player dialogue, follow-up wheel options, relationship deltas,
ceremony narration, and off-screen villa commits together in one inspectable
artifact.

## What felt off

This is a trace review, not a balance report. Read it for feel, continuity,
memories, and gossip surfacing rather than aggregate win-rate conclusions.

## Open questions

- Did the wheel choices feel Sims-like and short enough?
- Did off-screen villa commits make the world feel alive?
- Did memories and gossip surface at the right level of specificity?

Final hash: `{final_hash or "unknown"}`
"""


def infer_llm_mode(records: list[dict[str, Any]]) -> str:
    """Infer mock-vs-real mode for older traces that lack explicit metadata."""
    from src.game.agents.mock_dialogue import MOCK_NPC_LINES

    for record in records:
        exchange = record.get("exchange")
        if not isinstance(exchange, dict):
            continue
        player_line = str(exchange.get("player_dialogue", ""))
        npc_line = str(exchange.get("npc_dialogue", ""))
        # Current demo dialogue uses fixed NPC replies keyed by category.
        if npc_line in MOCK_NPC_LINES:
            return "mock"
        # Legacy signature (pre-2026 traces that echoed the menu label).
        if "I wanted to say this properly" in player_line and "*smiles* I hear you" in npc_line:
            return "mock"
    return "unknown"


def llm_mode_note(llm_mode: str) -> str:
    """Render an HTML-ready note for a trace LLM mode."""
    if llm_mode == "mock":
        return "Dialogue was generated by deterministic mock agents for coverage, not by the real LLM voice."
    if llm_mode == "real":
        return "Dialogue and agent commits came from live LLM calls recorded into this trace."
    return "This older trace does not declare whether dialogue came from mock or real LLM agents."


def plain_llm_mode_note(llm_mode: str) -> str:
    """Render a markdown note for a trace LLM mode."""
    if llm_mode == "mock":
        return "Use this packet to verify mechanics and dashboard coverage, not final dialogue quality."
    if llm_mode == "real":
        return "Use this packet to judge both mechanics and dialogue feel."
    return "Mode is unknown because the trace predates explicit `llm_mode` metadata."


def repro(trace_path: Path, out: Path) -> str:
    """Render reproduction commands markdown."""
    trace = trace_path.as_posix()
    output = out.as_posix()
    return f"""# How To Reproduce

```bash
uv run python -m src.game.cli play --record {trace}
uv run python -m src.game.cli play --replay {trace}
uv run python -m src.game.cli report packet --trace {trace} --out {output}
uv run python -m src.game.cli verify --playthrough {trace}
uv run python -m src.game.cli verify --all
```
"""
